language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

before_install:
    - sudo apt-get -qq update
    - pip install --upgrade pip setuptools

install: 
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install -e .

script: 
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test --cov=magma tests;else pytest --cov=magma tests; fi
