language: python
python:
    - "3.6"

sudo: false

cache:
    apt: true

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test  # g++-4.9 for coreir
    packages:
        - g++-4.9  # for coreir

before_install:
    - source .travis/install_coreir.sh

install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install -e .

script:
    - py.test --cov=magma tests/
