language: python
python:
    - "3.6"

sudo: true  # Needed for coreir-dev branch building coreir from source (installing g++-4.9 through apt)

before_install:
    - source .travis/install_coreir.sh

install:
    - pip install python-coveralls
    - pip install pytest-cov pytest-pep8
    - pip install -e .

script:
    - py.test --cov magma --pep8 magma -v --cov-report term-missing tests

after_success:
    - coveralls
