language: python
python:
    - "3.6"

before_install:
    # BEGIN: coreir installation
    - wget https://github.com/rdaly525/coreir/releases/download/v0.0.1/coreir.tar.gz
    - mkdir coreir_release
    - tar -xf coreir.tar.gz -C coreir_release --strip-components 1
    - export PATH=$TRAVIS_BUILD_DIR/coreir_release/bin:$PATH
    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/coreir_release/lib:$LD_LIBRARY_PATH
    - pip install coreir
    # END: coreir installation

install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install -e .

script:
    - py.test --cov=magma tests/
