language: python
python:
    - "3.6"

sudo: true

before_install:
    - source .travis/install_coreir.sh

install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install -e .

script:
    - py.test --cov=magma tests/
