language: python
python:
    - "3.6"

sudo: required  # for coreir install.sh

before_install:
    - ./.travis/install_coreir.sh

install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install -e .

script:
    - py.test --cov=magma tests/
