language: python
python:
    - "3.6"

sudo: true  # Needed for coreir-dev branch building coreir from source (installing g++-4.9 through apt)

before_install:
    - source .travis/install_coreir.sh

install:
    - pip install python-coveralls
    - pip install pytest-cov pytest-pep8
    - pip install -e .

script:
    # TODO: Enable pep8 check
    # - py.test --cov magma --pep8 magma -v --cov-report term-missing tests
    - py.test --cov magma -v --cov-report term-missing tests

after_success:
    - coveralls

# jobs:
#   include:
#     - stage: trigger downstream
#       jdk: oraclejdk8
#       script: |
#         echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
#         if [[ ($TRAVIS_BRANCH == master) &&
#               ($TRAVIS_PULL_REQUEST == false) ]] ; then
#           curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
#           sh trigger-travis.sh David-Durst aetherling $TRAVIS_ACCESS_TOKEN
#         fi
