language: python
python:
    - "3.6"

sudo: false

cache:
    apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test  # coreir (for g++-4.9)
    packages:
      - g++-4.9  # coreir

before_install:
    # BEGIN: coreir installation
    - mkdir deps
    - mkdir deps/bin
    - mkdir deps/lib
    - mkdir deps/include
    - cd deps
    - git clone https://github.com/rdaly525/coreir.git
    - cd coreir
    - export COREIRCONFIG="g++-4.9"
    - export COREIR=$PWD
    - make install prefix=$TRAVIS_BUILD_DIR/deps
    - cd ..
    - cd ..
    - export PATH=$TRAVIS_BUILD_DIR/deps/bin:$PATH
    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/deps/lib:$LD_LIBRARY_PATH
      # - pip install coreir
    - pip install git+git://github.com/leonardt/pycoreir.git
    # END: coreir installation

install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install -e .

script:
    - py.test --cov=magma tests/
